spring:
  datasource:
    url: jdbc:h2:mem:appdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update   # creates the table automatically for now
    open-in-view: false
  profiles:
    group:
      dev: postgres,kafka
management:
  endpoints.web.exposure.include: health,info,metrics,prometheus
  otlp.metrics.export.enabled: false   # make sure OTLP is off
  prometheus.metrics.export.enabled: true
  metrics:
    distribution:
      percentiles:
        http.server.requests: 0.5,0.95,0.99
      percentiles-histogram:
        http.server.requests: true
